# api-gateway configuration
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: wallet-auth
          uri: lb://wallet-service
          predicates:
            - Path=/api/v1/auth/**
        - id: wallet
          uri: lb://wallet-service
          predicates:
            - Path=/api/v1/wallets/me/**,/api/v1/users/**
        - id: inventory-public
          uri: lb://inventory-service
          predicates:
            - Path=/api/v1/products/**,/api/v1/categories/**
        - id: shop
          uri: lb://shop-service
          predicates:
            - Path=/api/v1/cart/**,/api/v1/wishlist/**,/api/v1/orders/**,/api/v1/reviews/**
